### ISSUE TITLE
Update config.sh file

### ISSUE THREAD

**Issue by cospeedster** [Telmate/terraform-ubuntu-proxmox-iso#4]
Hello,

please update the following in config.sh:

: ${VERSION:="14.04.5"}
: ${DISTRO:="server"}

with

: ${VERSION:="19.04"}
: ${DISTRO:="live-server"}

This may help others.

**Comment by cospeedster** [comment]
Okay, it seems that newer versions are not supported?
14.04 worked
18.04.3 not working
19.04 not working

**Comment by ggongaware** [comment]
Newer versions of proxmox support cloud-init, which is a more standard way to do everything this ISO was supposed to do.

**Comment by cospeedster** [comment]
Thank you! I'll try this way.

**Comment by codedChaos** [comment]
I was able to use 16.04.6 successfully. Attempting 18.04.4, now.
